codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: 80...100

  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 0%
        if_no_uploads: error
        if_ci_failed: error

    patch:
      default:
        enabled: yes
        target: 100%
        threshold: 0%
        if_no_uploads: error
        if_ci_failed: error

    changes:
      default:
        enabled: no

comment: false
