name: Required checks

on:
  pull_request:

jobs:
  testing:
    uses: ./.github/workflows/testing.yml

  required-checks:
    name: Required checks
    runs-on: ubuntu-22.04
    needs: [testing]
    steps:
      - run: echo "All required checks passed"
