name: Upload Package

on:
  release:
    types: [published]

jobs:
  build-and-publish-python-package:
    name: Build Python package with sources and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Build a package
        run: python setup.py sdist
      - name: Install dependencies
        run: pip install twine
      - name: Publish to private PyPI
        run: python -m twine upload dist/* -u __token__ -p ${{ secrets.pypi_token }}
