name: Upload Package

on:
  release:
    types: [published]

jobs:
  build-and-publish-python-package:
    name: Build Python package with sources and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - name: Build a package
        run: poetry build
      - name: Publish to private PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.pypi_token }}
          poetry publish
