name: Upload Package

on:
  release:
    types: [published]

jobs:
  build-and-publish-python-package:
    name: Build Python package with sources and publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build and publish to PyPi
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
